version: "3.9"
services:

  # Apache a PHP
  www:
    build: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8080:80

  node:
    image: "node:24"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app
    ports:
      - "8888:8888"
    command: ["npm", "install"]